const products = [
    {
      id: 1,
      name: "Floral Essence",
      description: "A fresh, floral fragrance with notes of jasmine, rose, and lily.",
      brand: "Essence",
      price: 49.99,
      quantity: 100,
      category: "Women",
      rating: 4.5,
      imageUrl: "https://wallpapers.com/images/hd/aromatic-perfume-essence-png-05242024-6i4mgu857k62z1i8.png",
      fragranceNotes: ["Jasmine", "Rose", "Lily"],
      size: "100ml",
      launchDate: "2021-05-15",
    },
    {
      id: 2,
      name: "Citrus Breeze",
      description: "A vibrant, citrusy perfume with a hint of musk and wood.",
      brand: "Breeze",
      price: 39.99,
      quantity: 150,
      category: "Unisex",
      rating: 4.3,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Lemon", "Orange", "Musk"],
      size: "50ml",
      launchDate: "2020-03-20",
    },
    {
      id: 3,
      name: "Ocean Mist",
      description: "A refreshing aquatic scent with notes of sea salt, marine, and mint.",
      brand: "Aqua",
      price: 55.99,
      quantity: 90,
      category: "Men",
      rating: 4.7,
      imageUrl: "http://pngimg.com/uploads/perfume/perfume_PNG10303.png",
      fragranceNotes: ["Sea Salt", "Marine", "Mint"],
      size: "75ml",
      launchDate: "2022-01-10",
    },
    {
      id: 4,
      name: "Vanilla Spice",
      description: "A warm, spicy scent with rich vanilla and cinnamon undertones.",
      brand: "Spice & Co.",
      price: 45.00,
      quantity: 200,
      category: "Women",
      rating: 4.8,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Vanilla", "Cinnamon", "Sandalwood"],
      size: "120ml",
      launchDate: "2019-07-18",
    },
    {
      id: 5,
      name: "Midnight Woods",
      description: "A deep, mysterious scent with notes of sandalwood, oud, and amber.",
      brand: "Nightfall",
      price: 59.99,
      quantity: 70,
      category: "Men",
      rating: 4.6,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["Sandalwood", "Oud", "Amber"],
      size: "90ml",
      launchDate: "2020-11-25",
    },
    {
      id: 6,
      name: "Lavender Bliss",
      description: "A calming lavender perfume with hints of chamomile and bergamot.",
      brand: "Bliss",
      price: 40.99,
      quantity: 85,
      category: "Unisex",
      rating: 4.4,
      imageUrl: "http://pngimg.com/uploads/perfume/perfume_PNG10303.png",
      fragranceNotes: ["Lavender", "Chamomile", "Bergamot"],
      size: "60ml",
      launchDate: "2021-08-10",
    },
    {
      id: 7,
      name: "Amber Night",
      description: "A rich, warm scent with amber, patchouli, and vanilla.",
      brand: "Amber Co.",
      price: 65.00,
      quantity: 60,
      category: "Women",
      rating: 4.9,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Amber", "Patchouli", "Vanilla"],
      size: "100ml",
      launchDate: "2022-02-01",
    },
    {
      id: 8,
      name: "Fresh Forest",
      description: "A crisp, woody scent with pine, cedar, and a touch of mint.",
      brand: "Forest",
      price: 54.99,
      quantity: 120,
      category: "Men",
      rating: 4.2,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["Pine", "Cedar", "Mint"],
      size: "85ml",
      launchDate: "2021-06-20",
    },
    {
      id: 9,
      name: "Rose Petals",
      description: "A soft, romantic scent with rose, peony, and a hint of musk.",
      brand: "Rose Boutique",
      price: 42.50,
      quantity: 130,
      category: "Women",
      rating: 4.7,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Rose", "Peony", "Musk"],
      size: "75ml",
      launchDate: "2020-09-15",
    },
    {
      id: 10,
      name: "Coconut Dream",
      description: "A tropical, creamy scent with coconut, vanilla, and sandalwood.",
      brand: "Dream Perfumes",
      price: 47.99,
      quantity: 110,
      category: "Unisex",
      rating: 4.5,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["Coconut", "Vanilla", "Sandalwood"],
      size: "100ml",
      launchDate: "2019-11-30",
    },
    {
      id: 11,
      name: "Spicy Ember",
      description: "An intense, smoky scent with rich spices and burning wood.",
      brand: "Ember & Co.",
      price: 72.00,
      quantity: 50,
      category: "Men",
      rating: 4.8,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Spices", "Burning Wood", "Tobacco"],
      size: "90ml",
      launchDate: "2021-12-10",
    },
    {
      id: 12,
      name: "Morning Dew",
      description: "A fresh and light scent with dewdrops, green leaves, and soft florals.",
      brand: "Dew Fragrance",
      price: 38.50,
      quantity: 150,
      category: "Women",
      rating: 4.4,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["Dewdrops", "Green Leaves", "Floral"],
      size: "70ml",
      launchDate: "2020-04-05",
    },
    {
      id: 13,
      name: "Golden Amber",
      description: "A luxurious, radiant fragrance with amber, sandalwood, and saffron.",
      brand: "Golden Scent",
      price: 85.00,
      quantity: 45,
      category: "Unisex",
      rating: 4.9,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Amber", "Sandalwood", "Saffron"],
      size: "120ml",
      launchDate: "2019-08-21",
    },
    {
      id: 14,
      name: "Cedarwood Drift",
      description: "A rugged, woody scent with cedar, oakmoss, and a touch of leather.",
      brand: "Woodlands",
      price: 57.99,
      quantity: 80,
      category: "Men",
      rating: 4.7,
      imageUrl: "http://pngimg.com/uploads/perfume/perfume_PNG10303.png",
      fragranceNotes: ["Cedar", "Oakmoss", "Leather"],
      size: "100ml",
      launchDate: "2021-10-30",
    },
    {
      id: 15,
      name: "Pearl Blossom",
      description: "A delicate, floral scent with white lilies, magnolia, and vanilla.",
      brand: "Pearl Fragrances",
      price: 60.50,
      quantity: 95,
      category: "Women",
      rating: 4.5,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["White Lilies", "Magnolia", "Vanilla"],
      size: "100ml",
      launchDate: "2022-03-25",
    },
    {
      id: 16,
      name: "Cinnamon Flame",
      description: "A spicy, warming scent with cinnamon, clove, and black pepper.",
      brand: "Flame & Spice",
      price: 43.99,
      quantity: 120,
      category: "Unisex",
  rating: 4.3,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Cinnamon", "Clove", "Black Pepper"],
      size: "75ml",
      launchDate: "2020-01-17",
    },
    {
      id: 17,
      name: "Minty Fresh",
      description: "A crisp, cooling fragrance with fresh mint, basil, and a hint of eucalyptus.",
      brand: "Herbal Fresh",
      price: 35.00,
      quantity: 140,
      category: "Unisex",
      rating: 4.1,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["Mint", "Basil", "Eucalyptus"],
      size: "50ml",
      launchDate: "2021-05-30",
    },
    {
      id: 18,
      name: "Sandalwood Calm",
      description: "A tranquil blend of sandalwood, lavender, and soft musks for relaxation.",
      brand: "Calm Scents",
      price: 53.99,
      quantity: 75,
      category: "Unisex",
      rating: 4.6,
      imageUrl: "http://pngimg.com/uploads/perfume/perfume_PNG10303.png",
      fragranceNotes: ["Sandalwood", "Lavender", "Musk"],
      size: "100ml",
      launchDate: "2020-08-22",
    },
    {
      id: 19,
      name: "Berry Crush",
      description: "A playful, sweet scent with strawberry, raspberry, and vanilla notes.",
      brand: "Crush",
      price: 48.99,
      quantity: 100,
      category: "Women",
      rating: 4.4,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["Strawberry", "Raspberry", "Vanilla"],
      size: "75ml",
      launchDate: "2019-06-14",
    },
    {
      id: 20,
      name: "Citrus Splash",
      description: "A zesty citrus blend with orange, grapefruit, and a touch of lime.",
      brand: "Citrus & Co.",
      price: 39.99,
      quantity: 110,
      category: "Unisex",
      rating: 4.3,
      imageUrl: "https://www.pngall.com/wp-content/uploads/13/Chanel-Perfume-PNG-Cutout.png",
      fragranceNotes: ["Orange", "Grapefruit", "Lime"],
      size: "100ml",
      launchDate: "2019-09-25",
    },
    {
      id: 21,
      name: "Oud Royale",
      description: "An exotic and luxurious scent with oud, saffron, and leather notes.",
      brand: "Royale Scents",
      price: 120.00,
      quantity: 30,
      category: "Unisex",
      rating: 4.9,
      imageUrl: "http://www.pngall.com/wp-content/uploads/2016/05/Perfume-Free-Download-PNG.png",
      fragranceNotes: ["Oud", "Saffron", "Leather"],
      size: "125ml",
      launchDate: "2018-12-12",
    },
    {
      id: 22,
      name: "Frosted Pine",
      description: "A cool, woody scent with pine, fir, and winter mint for freshness.",
      brand: "Winter Fresh",
      price: 45.50,
      quantity: 85,
      category: "Men",
      rating: 4.5,
      imageUrl: "https://www.pngall.com/wp-content/uploads/13/Chanel-Perfume-PNG-Cutout.png",
      fragranceNotes: ["Pine", "Fir", "Winter Mint"],
      size: "85ml",
      launchDate: "2021-12-01",
    },
    {
      id: 23,
      name: "Cherry Blossom",
      description: "A delicate and romantic scent with cherry blossoms, jasmine, and vanilla.",
      brand: "Blossom Beauty",
      price: 55.00,
      quantity: 100,
      category: "Women",
      rating: 4.6,
      imageUrl: "http://pngimg.com/uploads/perfume/perfume_PNG10303.png",
      fragranceNotes: ["Cherry Blossom", "Jasmine", "Vanilla"],
      size: "100ml",
      launchDate: "2019-04-18",
    },
    {
      id: 24,
      name: "Velvet Night",
      description: "A rich, seductive fragrance with notes of dark chocolate, amber, and musk.",
      brand: "Velvet",
      price: 68.00,
      quantity: 55,
      category: "Men",
      rating: 4.7,
      imageUrl: "https://www.pngall.com/wp-content/uploads/13/Chanel-Perfume-PNG-Cutout.png",
      fragranceNotes: ["Dark Chocolate", "Amber", "Musk"],
      size: "100ml",
      launchDate: "2022-07-04",
    },
    {
      id: 25,
      name: "Wild Rose",
      description: "A bold, floral perfume with wild rose, geranium, and a touch of honey.",
      brand: "Wild Scents",
      price: 58.99,
      quantity: 95,
      category: "Women",
      rating: 4.5,
      imageUrl: "https://pluspng.com/img-png/perfume-hd-png-perfume-png-picture-png-image-1000.png",
      fragranceNotes: ["Wild Rose", "Geranium", "Honey"],
      size: "75ml",
      launchDate: "2020-06-19",
    },
  ];
  
  export default products